name: React CI Pipeline

on:
  push:
    branches:
      - production
      - staging
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 22

    - name: Install Dependencies
      run: npm install
      working-directory: servicepro

    - name: Build Project
      run: npm run build
      working-directory: servicepro
